version: "3.9"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root2
      MYSQL_DATABASE: inventory_docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot2"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/inventory_docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root2
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-network

  react-frontend:
    build:
      context: ./../inventario-frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - spring-app
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge
